data:
  drop_last: false
  is_DDP: false
  is_meta: true
  num_query: 15
  test_batchsize: 8
  test_data_root: ../data/libfewshot/miniImageNet
  test_dataset_name: miniImageNet_clip
  test_num_task: 2000
  test_shot: 1
  test_way: 5
  train_batchsize: 4
  train_data_root: ../data/libfewshot/miniImageNet
  train_dataset_name: miniImageNet_clip
  train_num_task_per_epoch: 1000
  train_num_workers: 8
  train_shot: 5
  train_way: 5
  val_batchsize: 8
  val_num_task: 1000
  val_num_workers: 8
  val_shot: 1
  val_test_data_root: ../data/libfewshot/miniImageNet
  val_test_dataset_name: miniImageNet_clip
  val_way: 5
is_test: false
load_backbone_only: false
load_pretrained: true
model:
  backbone_name: ViT_B_32_clip
  decay_scheduler: cosine
  lr: 5.0e-05
  metric: cosine
  normalize: true
  num_query: 15
  optim_type: sgd
  scale_cls: 10.0
  test_batch_size_per_gpu: 8
  test_shot: 1
  test_way: 5
  train_batch_size_per_gpu: 4
  train_shot: 5
  train_way: 5
  val_batch_size_per_gpu: 8
  val_shot: 1
  val_way: 5
  weight_decay: 0.0005
model_name: FD_Align_SCP_meta
pre_trained_path: null
seed: 10
trainer:
  accelerator: null
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      mode: max
      monitor: val/acc
      save_last: true
      verbose: true
  - class_path: callbacks.SetSeedCallback
    init_args:
      is_DDP: false
      seed: 10
  fast_dev_run: false
  gpus:
  - 0
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      id: FDAlign
      log_model: true
      name: PN_FDAlign/1shot/FDAlign
      project: CLIPFT
      save_dir: ./results/PN_FDAlign/1shot
  max_epochs: 60
  replace_sampler_ddp: false
  resume_from_checkpoint: null
  sync_batchnorm: false
